module "github_repository_minimal" {
  # Swap sources. These docs are autogenerated from actual terraform tests.
  # source = "https://registry.terraform.io/modules/codelawcorp/repository/github/latest"
  source = "../../"
  name   = "test-${basename(path.root)}"


  archive_on_destroy = false # Not a critical repo
}

