module "github_repository_minimal" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin version

  name = "test-${basename(abspath(path.root))}"


  archive_on_destroy = false # Not a critical repo
}

