#!/usr/bin/env bash
set -e

echo "Running pre-commit hooks"

npx validate-branch-name -r '^(prod|stg|dev)$|^(feature|fix|hotfix)/.+$'

echo "Formatting tf files"
cd $(git rev-parse --show-toplevel)
terraform fmt -check -recursive || { terraform fmt -write=true -recursive && exit 1; } && echo "Files are well-formatted"



terraform validate

# GITHUB_OWNER=codelawcorp-test terraform test

gitleaks git --staged

