#!/usr/bin/env bash
set -e

# # Track the currently executing command for better debug output
# trap 'last_cmd=$cur_cmd; cur_cmd=$BASH_COMMAND' DEBUG



echo "Running pre-commit hooks"

npx validate-branch-name -r '^(prod|stg|dev)$|^(feature|fix|hotfix)/.+$'

echo "Formatting tf files"
cd $(git rev-parse --show-toplevel)
terraform fmt -check -recursive || { terraform fmt -write=true -recursive && exit 1; } && echo "Files are well-formatted"



terraform validate

# GITHUB_OWNER=codela   wcorp-test terraform test

gitleaks git --staged

