# main.tf
module "this" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin the version

  name        = "bootstrap" # Evaluates to the current directory name
  description = "This repository manages itself as code. Also it will manage other repositories in the future."

  archive_on_destroy = false

  bootstrap_me = true
}

