# main.tf
module "this" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin the version

  name        = basename(abspath(path.root)) # Evaluates to the current directory name
  description = "This repository manages itself as code. Also it will manage other repositories in the future."

  archive_on_destroy = false

  bootstrap_tf_cloud = { # This is example. Replace with your own valued
    tf_cloud_organization = var.tf_cloud_organization
    tf_cloud_workspace    = var.tf_cloud_workspace
    terraform_version     = try(file("${abspath(path.root)}/.terraform-version"), "latest")
    tf_cloud_token        = var.tf_cloud_token
    github_token          = var.github_token
  }
}

variable "tf_cloud_organization" {
  description = "Terraform Cloud Organization name. Create it manually first."
  type        = string
}

variable "tf_cloud_workspace" {
  description = "Terraform Cloud Workspace name. Create it manually first."
  type        = string
}


variable "tf_cloud_token" {
  description = "Terraform Cloud token. Create it manually first."
  type        = string
  sensitive   = true
}

variable "github_token" {
  description = "GitHub token. Create it manually first."
  type        = string
  sensitive   = true
}

output "help_message" {
  description = "Help message"
  value       = "After the first apply run `terraform init` again. Answer 'yes' to the prompt about migrating the existing state."
}


