formatter: "markdown" # this is required

version: "v0.20.0" # terraform-docs version

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true # deprecated in v0.13.0, removed in v0.15.0

content: |
  {{ .Header }}
  # Examples
  ### Minimal example
  ```hcl
  {{ include "examples/minimal/main.tf" }}
  ```

  For more examples, scroll to the button below.  

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}



  The benifit of this and other modules is that it **bundles all resources related to `github_repository`** and abstract complexities of github provider.  
  The best effort was made to match the variablesdefault values with provider's defaults to avoid confusions.  
  Instead of using variable prefixes, many resources are organized into nested objects: e.g. `branch -> branch protection, environment -> environment protection`.
  When a variable is an object, there is a comment with a link to the provider's documentation for the related resource.
  

  `auto_init` is always true for other resources to work.  
  `default_branch` is always set to `prod` when not using a template. This can be changed to `main` if needed. See [explanation](https://medium.com/@maximonyshchenko/the-best-git-branching-strategy-65abceb67e6a) why `prod` is preferred over `main`.
  ➡️ Scroll right ➡️ to see Default values.
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

  ## More examples
  ### Bootstrap aka chicken-egg example - manage the repository where this module is used
    ```hcl
  {{ include "examples/bootstrap/main.tf" }}
  ```

  ### Complete example
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```


  ### Importing existing repository example
  The best part about importing existing resources is that provider does not treat existing configurations as existing resources, but simply overwrites them. You only have to import `github_repository` resource.  
  ```hcl
  import {
    to = module.quick_ops.github_repository.this
    id = "quick-ops"
  }
  module "quick_ops" {
    source = "codelawcorp/repository/github"
    # version = "~> 2.0.0"  # It is always recommended to pin the version

    name        = "quick_ops"
    description = "Scripting magic. Like Ansible ad-hoc but with iterm2"
    visibility  = "public"

    archive_on_destroy = true
  }

  ```

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
