formatter: "markdown" # this is required

version: "v0.20.0" # terraform-docs version

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true # deprecated in v0.13.0, removed in v0.15.0

content: |
  {{ .Header }}
  # Examples
  ### Minimal example
  ```hcl
  {{ include "example/minimal.tf" }}
  ```

  ### Complete example
  ```hcl
  {{ include "example/complete.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  We used best effort to make sure that default values match provider's defaults to avoid confusions.  
  Instead of using variable prefixes, we use nested objects: e.g. `branch -> branch protection, environment -> environment protection`. This naturally leads to more readable code, which is one of the goals of this module.
  When variable is an object, there is a comment with a link to the provider's documentation for the related resource.
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false 
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true 
  required: true
  sensitive: true
  type: true
