module "github_repository_fork" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin version

  name         = "test-${basename(abspath(path.root))}"
  fork         = true
  source_owner = "terraform-aws-modules"
  source_repo  = "terraform-aws-vpc"


  archive_on_destroy = false # Not a critical repo
}



