module "this" {
  # Swap sources. These docs are autogenerated from actual terraform tests.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin the version

  name        = basename(abspath(path.root)) # Evaluates to the current directory name
  description = "This repository manages itself as code. Also it will manage other repositories in the future."

  archive_on_destroy = false

  bootstrap_tf_cloud = {
    tf_cloud_organization = "magzim21" # This is example. Replace with your organization name.
    tf_cloud_workspace    = "github"   # This is example. Replace with your workspace name.
    terraform_version     = try(file("${abspath(path.root)}/.terraform-version"), "latest")
    tf_cloud_token        = var.tf_cloud_token
  }
}

variable "tf_cloud_token" {
  description = "Terraform Cloud token"
  type        = string
  sensitive   = true
  # default = null # uncomment after the first apply
  nullable = true
}

output "help_message" {
  description = "Help message"
  value       = "After the first apply run `terraform init` again. Answer 'yes' to the prompt about migrating the existing state."
}


