module "branch_variation_with_template_not_listed_default_branch" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0" # It is always recommended to pin version

  name        = "test-${basename(abspath(path.root))}-2"
  description = "An example repository created using Terraform"
  visibility  = "public"

  archive_on_destroy = false


  # Template configuration (if using a template repository)
  template = {
    owner                = "codelawcorp"
    repository           = "template"
    include_all_branches = true # TODO / try without this
  }

  default_branch = "not-from-the-branches-list"
  branches = [
    {
      name = "prod" # Try test without prod
    },
  ]

}

module "branch_variation_listed_default_branch" {
  # Swap sources. These docs are autogenerated.
  # source = "codelawcorp/repository/github"
  source = "../../"
  # version = "~> 2.0.0" # It is always recommended to pin version
  name        = "test-${basename(abspath(path.root))}" # Any repository name.
  description = "An example repository created using Terraform"
  visibility  = "private"

  archive_on_destroy = false


  default_branch = "prod"
  branches = [
    {
      name = "prod" # Try test without prod
    },
  ]

}



# try main branch in a list of branches