---
name: main
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} 🏗️
on:
  push:
    branches:
      - prod
      - stg
      - dev
  schedule: # A regular sync to prevent drifts.
    - cron: "0 8 * * 1" # every day at 8am UTC Monday # https://crontab.guru/#0_8_*_*_*
  workflow_dispatch: {}
env:
  APP_NAME: ${{ vars.APP_NAME }}        # Set via GitHub Secrets and variables on a repo level
  # AWS_REGION: ${{ vars.AWS_REGION }} # Set via GitHub Secrets and variables on a org level
  # AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}  # Set via GitHub Secrets and variables on a org level
#   ROLE_ARN: ${{ secrets.ROLE_ARN }}     # Set via GitHub Secrets on a repo level
jobs:
  tests:
    name: Run Tests
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetching all history to scan for secrets

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
          GITLEAKS_VERSION: 8.24.3

      - name: Setup Node.js for commitlint
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Check if the commit message is properly formatted
        run: |
          npm install -g @commitlint/config-conventional
          npx commitlint --config ".githooks/.commitlintrc.yml" --last --verbose

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: Check if terraform is well formatted
        run: terraform fmt -recursive  -check
      
      - name: Run Terraform init
        run: terraform init
      - name: Run Terraform tests
        # USE PAT_TOKEN instead of GITHUB_TOKEN, to get admin access to the test org.
        run: GITHUB_TOKEN=${{ secrets.PAT_TOKEN }} GITHUB_OWNER=codelawcorp-test terraform test

  terraform-docs:
    name: Generate Terraform Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Render terraform docs inside the README.md and push changes
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          git-push: "true"
          # git-push-sign-off: "true"

  next-version:
    name: Determine the next version
    runs-on: ubuntu-latest
    needs:
      - tests
    permissions:
      contents: write # to be able to publish a GitHub release
    outputs:
      should-run-build: ${{ steps.decision.outputs.should-run-build }}
      semver_tag: ${{ steps.decision.outputs.semver_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js for semantic-release
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Decide whether to release
        id: decision
        # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # TODO / remove this
        run: |
          # Check if there are any changes that are relevant for the release
          SEMVER_TAG=$(npx semantic-release --dry-run | awk '/The next release version is/ {print $NF}')
          if [[ -n "${SEMVER_TAG}" ]]; then
            echo "should-run-build=True" >> "$GITHUB_OUTPUT"
            echo "semver_tag=$SEMVER_TAG" >> $GITHUB_OUTPUT
            echo "#### Found features/fixes. The next version will be ${SEMVER_TAG}... :punch:" | tee -a $GITHUB_STEP_SUMMARY
          else
            echo "should-run-build=False" >> "$GITHUB_OUTPUT"
            echo "#### No features, no fixes. Skipping Build job :police_car:" | tee -a $GITHUB_STEP_SUMMARY
          fi


  git-tag-release:
    name: Create ${{ needs.next-version.outputs.semver_tag }} git tag
    runs-on: ubuntu-latest
    needs:
      - next-version
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js for semantic-release
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Create a semanitc git tag  
        # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # TODO / remove this
        run: |
          npx semantic-release
          echo "#### Created a git tag ${{ needs.next-version.outputs.semver_tag }} 🐙" | tee -a $GITHUB_STEP_SUMMARY